name: Simple chat Tmaior action

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development
    env:
      # AWS
      AWS_REGION: us-east-1
      AWS_IMAGE_TAG: latest
      AWS_IMAGE: tmaior-test-simple-chat

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: |
          chmod +x ${{github.workspace}}/iac/deploy.sh 
          ${{github.workspace}}/iac/deploy.sh "${{ env.AWS_IMAGE }}" "${{ env.AWS_IMAGE_TAG }}" "${{ env.AWS_REGION }}" "${{ secrets.AWS_ACCOUNT_ID }}" "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}"