name: Simple chat Tmaior action

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development
    env:
      # AWS
      AWS_REGION: us-east-1
      AWS_IMAGE_TAG: latest
      AWS_IMAGE: tmaior-test-simple-chat

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Create env file'
        run: |
          touch .env
          echo DATABASE_URL="\"${{ secrets.DATABASE_URL }}\"" >> .env
          cat .env
          ls -a


      - name: Deploy
        run: |
          chmod +x ${{github.workspace}}/iac/deploy.sh 
          ${{github.workspace}}/iac/deploy.sh "${{ env.AWS_IMAGE }}" "${{ env.AWS_IMAGE_TAG }}" "${{ env.AWS_REGION }}" "${{ secrets.AWS_ACCOUNT_ID }}" "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Connect to EC2 instance, update and run Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-18-234-171-130.compute-1.amazonaws.com "
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com;
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_IMAGE }}:${{ env.AWS_IMAGE_TAG }};
            docker stop \u0024(docker ps -a -q);
            docker rm \u0024(docker ps -a -q);
            docker run -d -p 3000:3000 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_IMAGE }}:${{ env.AWS_IMAGE_TAG }};
          "